[package]
name = "otti"
version = "0.2.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2018"
resolver = "2"
license = "AGPL-3.0-only"

[dependencies]
anyhow = "1.0.41"
arboard = "1.2.1"
crossbeam-channel = "0.5.1"
crossterm = "0.19.0"
indoc = "1.0.3"
otti-core = { path = "./otti-core" }
otti-gen = { path = "./otti-gen" }
otti-store = { path = "./otti-store" }
provider-aegis = { path = "./provider-aegis" }
provider-andotp = { path = "./provider-andotp" }
provider-authpro = { path = "./provider-authpro" }
rpassword = "5.0.1"
rprompt = "1.0.5"
secrecy = "0.7.0"
structopt = "0.3.22"
tui = { version = "0.15.0", default-features = false, features = ["crossterm"] }

[profile.release]
lto = true

[workspace]
members = [
    "otti-core",
    "otti-gen",
    "otti-store",
    "provider-aegis",
    "provider-andotp",
    "provider-authpro",
]
