[workspace]
members = [
    "otti-core",
    "otti-gen",
    "otti-store",
    "provider-aegis",
    "provider-andotp",
    "provider-authpro",
]
resolver = "2"

[workspace.package]
version = "0.2.5"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-only"

[package]
name = "otti"
publish = false
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0.65"
arboard = { version = "3.1.0", default-features = false }
clap = { version = "4.0.4", features = ["derive"] }
clap_complete = "4.0.2"
clap_mangen = "0.2.2"
crossbeam-channel = "0.5.6"
crossterm = "0.25.0"
indoc = "1.0.7"
otti-core = { path = "./otti-core" }
otti-gen = { path = "./otti-gen" }
otti-store = { path = "./otti-store" }
provider-aegis = { path = "./provider-aegis" }
provider-andotp = { path = "./provider-andotp" }
provider-authpro = { path = "./provider-authpro" }
rpassword = "7.0.0"
rprompt = "1.0.5"
secrecy = "0.8.0"
tui = { version = "0.19.0", default-features = false, features = ["crossterm"] }

[profile.release]
lto = true
strip = true
