[package]
name = "otti"
version = "0.2.1"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
resolver = "2"
license = "AGPL-3.0-only"

[dependencies]
anyhow = "1.0.52"
arboard = { version = "2.0.1", default-features = false }
clap = { version = "3.0.1", features = ["derive"] }
clap_complete = "3.0.1"
crossbeam-channel = "0.5.1"
crossterm = "0.20.0"
indoc = "1.0.3"
otti-core = { path = "./otti-core" }
otti-gen = { path = "./otti-gen" }
otti-store = { path = "./otti-store" }
provider-aegis = { path = "./provider-aegis" }
provider-andotp = { path = "./provider-andotp" }
provider-authpro = { path = "./provider-authpro" }
rpassword = "5.0.1"
rprompt = "1.0.5"
secrecy = "0.8.0"
tui = { version = "0.16.0", default-features = false, features = ["crossterm"] }

[profile.release]
lto = true

[workspace]
members = [
    "otti-core",
    "otti-gen",
    "otti-store",
    "provider-aegis",
    "provider-andotp",
    "provider-authpro",
]
