[licenses]
allow-osi-fsf-free = "both"
exceptions = [
    { allow = ["AGPL-3.0"], name = "otti", version = "*" },
    { allow = ["AGPL-3.0"], name = "otti-core", version = "*" },
    { allow = ["AGPL-3.0"], name = "otti-gen", version = "*" },
    { allow = ["AGPL-3.0"], name = "otti-store", version = "*" },
    { allow = ["AGPL-3.0"], name = "provider-aegis", version = "*" },
    { allow = ["AGPL-3.0"], name = "provider-andotp", version = "*" },
    { allow = ["AGPL-3.0"], name = "provider-authpro", version = "*" },
]

[bans]
skip = [
    { name = "aes", version = "=0.7.5" },
    { name = "cipher", version = "=0.3.0" },
    { name = "parking_lot", version = "=0.11.2" },
    { name = "parking_lot_core", version = "=0.8.5" },
]
