[licenses]
allow-osi-fsf-free = "both"
exceptions = [
    { allow = ["Unicode-DFS-2016"], name = "unicode-ident" },
]

[licenses.private]
ignore = true

[bans]
skip = [
    { name = "windows-sys", version = "=0.42.0" },
]
