[package]
name = "provider-andotp"
version = "0.2.1"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
aes-gcm = { version = "0.9.4", features = ["std"] }
bytes = "1.1.0"
hmac = "0.11.0"
otti-core = { path = "../otti-core" }
pbkdf2 = { version = "0.9.0", default-features = false }
rand = "0.8.4"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
sha-1 = "0.9.8"
thiserror = "1.0.30"

[dev-dependencies]
pretty_assertions = "1.0.0"
