[package]
name = "provider-andotp"
version = "0.2.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2018"
license = "AGPL-3.0-only"

[dependencies]
aes-gcm = { version = "0.9.2", features = ["std"] }
bytes = "1.0.1"
hmac = "0.11.0"
otti-core = { path = "../otti-core" }
pbkdf2 = { version = "0.8.0", default-features = false }
rand = "0.8.4"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
sha-1 = "0.9.6"
thiserror = "1.0.26"

[dev-dependencies]
pretty_assertions = "0.7.2"
