[package]
name = "otti-store"
version = "0.2.3"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
directories = "4.0.1"
flate2 = "1.0.24"
orion = "0.17.2"
otti-core = { path = "../otti-core" }
rmp-serde = "1.1.1"
secrecy = "0.8.0"
serde = { version = "1.0.145", features = ["derive"] }
thiserror = "1.0.37"
