[package]
name = "otti-store"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2018"
license = "AGPL-3.0-only"

[dependencies]
directories-next = "2.0.0"
flate2 = "1.0.20"
orion = "0.16.0"
otti-core = { path = "../otti-core" }
rmp-serde = "0.15.5"
secrecy = "0.7.0"
serde = { version = "1.0.126", features = ["derive"] }
thiserror = "1.0.26"
