[package]
name = "otti-store"
publish = false
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
directories = "4.0.1"
flate2 = "1.0.25"
orion = "0.17.2"
otti-core = { path = "../otti-core" }
rmp-serde = "1.1.1"
secrecy = "0.8.0"
serde = { version = "1.0.148", features = ["derive"] }
thiserror = "1.0.37"
