[package]
name = "otti-store"
version = "0.2.1"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
directories-next = "2.0.0"
flate2 = "1.0.22"
orion = "0.17.1"
otti-core = { path = "../otti-core" }
rmp-serde = "1.0.0"
secrecy = "0.8.0"
serde = { version = "1.0.136", features = ["derive"] }
thiserror = "1.0.30"
