[package]
name = "provider-authpro"
version = "0.2.3"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
aes = "0.8.1"
base64 = "0.13.0"
block-padding = { version = "0.3.2", features = ["std"] }
bytes = "1.1.0"
cbc = { version = "0.1.2", features = ["std"] }
hmac = "0.12.1"
otti-core = { path = "../otti-core" }
pbkdf2 = { version = "0.11.0", default-features = false }
rand = "0.8.5"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
serde_repr = "0.1.7"
sha-1 = "0.10.0"
thiserror = "1.0.30"

[dev-dependencies]
maplit = "1.0.2"
pretty_assertions = "1.2.0"
