[package]
name = "provider-authpro"
version = "0.2.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
aes = "0.7.5"
base64 = "0.13.0"
block-modes = "0.8.1"
bytes = "1.1.0"
hmac = "0.11.0"
otti-core = { path = "../otti-core" }
pbkdf2 = "0.9.0"
rand = "0.8.4"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
serde_repr = "0.1.7"
sha-1 = "0.9.8"
thiserror = "1.0.30"

[dev-dependencies]
pretty_assertions = "1.0.0"
