[package]
name = "otti-gen"
version = "0.2.1"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
hmac = { version = "0.12.1", features = ["std"] }
otti-core = { path = "../otti-core" }
sha-1 = "0.10.0"
sha2 = "0.10.2"
thiserror = "1.0.31"
